### ISSUE TITLE
Curl's globbing feature interferes with curly and square brackets inside the message

### ISSUE THREAD

**Issue by plonerma** [0mar/telegram-alert#2]
Hey, thanks for publishing this super useful script!
There is one small change I would suggest: you might want to turn of [globbing](https://ec.haxx.se/cmdline/cmdline-globbing) when using curl (using the `--globoff` option), so curly and square brackets can be used inside the message.

**Comment by 0mar** [comment]
Thanks for the helpful feedback and glad it is of some use! Closed in ab4f30e.
